### ISSUE TITLE
Grafana dashboards?

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-mixins#15]
Out of curiosity, how does these dashboard relate to the dashboards in the ceph repo at 

https://github.com/ceph/ceph/tree/f386db64332837dacf8f45ec13aa07ca7d6a0b1d/monitoring/grafana/dashboards

cc @jan--f

**Comment by shtripat** [comment]
@sebastian-philipp The dashboards maintained as part of this project (in case we do that someday), would be more taregeted for openshift usecase where ceph would be used as native storage. In such a scenario lot of dashboards which have detailed view of ceph cluster might not be applicable and more of abstract information without expsosing too much ceph internals, would be depicted in the dashboards here.
Also mixins are the way to add alerting rules, grafana dashboards and recording rules for openshift, so this project.

Hope this makes clear.

**Comment by sebastian-philipp** [comment]
Thanks!
