### ISSUE TITLE
Grafana Dependency Not Required

### ISSUE THREAD

**Issue by umangachapagain** [ceph/ceph-mixins#27]
https://github.com/ceph/ceph-mixins/blob/e22dc261d79fe5a6601c91d5f529a6e3d1d3c072/extras/operator/jsonnet/kube-prometheus.libsonnet#L4

https://github.com/ceph/ceph-mixins/blob/e22dc261d79fe5a6601c91d5f529a6e3d1d3c072/extras/operator/jsonnet/kube-prometheus.libsonnet#L10-L12

**Comment by shtripat** [comment]
Closing as required PR merged
