### ISSUE TITLE
Make does not work for dashboard, alerts or rules

### ISSUE THREAD

**Issue by ghost** [ceph/ceph-mixins#33]
Makefile doesn't contain anything for prometheus_alerts, prometheus_rules or dashboards_out. when run you get:
ceph-mixins $ make prometheus_alerts.yaml
make: No rule to make target 'prometheus_alerts.yaml'.  Stop.
ceph-mixins $ make prometheus_rules.yaml
make:  No rule to make target 'prometheus_rules.yaml'.  Stop.
ceph-mixins $ make dashboards_out
make: No rule to make target 'dashboards_out'.  Stop.

When reading the Makefile there are no references to any of these items but when make is run w/o argument it only produces prometheus_alert_rules.yaml . 

What happened? No more dashboard,etc?

Directions says to do the following:
To generate Prometheus Alert file

$ make prometheus_alerts.yaml

To generate Prometheus Rule file

$ make prometheus_rules.yaml

To generate Grafana Dashboard configs

$ make dashboards_out

**Comment by shtripat** [comment]
@mlg805 currently we dont have any grafana dashboards as part of the repo. Also some cleanup required for make file as unwanted stuff can be removed.

We will remove the unwanted make targets which are not applicable at the moment. Later if we add grafana dashboard, we will add the required targets.

**Comment by shtripat** [comment]
@anmolsachan can you look at this?

**Comment by ghost** [comment]
Perhaps remove those directions from the "read me" then if they are not valid.

**Comment by shtripat** [comment]
PR merged
