### ISSUE TITLE
Few general fixes required for 1.0

### ISSUE THREAD

**Issue by umangachapagain** [ceph/ceph-mixins#40]
https://github.com/ceph/ceph-mixins/blob/46e3c59f6341b9bdc8418588c74c80324311a097/extras/manifests/prometheus-rules.yaml#L5

Should be `prometheus: k8s`

https://github.com/ceph/ceph-mixins/blob/46e3c59f6341b9bdc8418588c74c80324311a097/extras/manifests/prometheus-rules.yaml#L7

Should be `prometheus-ceph-rules`

https://github.com/ceph/ceph-mixins/blob/46e3c59f6341b9bdc8418588c74c80324311a097/extras/manifests/prometheus-rules.yaml#L8

Should be `default`

**Comment by umangachapagain** [comment]
filename should be `prometheus-ceph-rules.yaml`

**Comment by shtripat** [comment]
Closing as required changes merged
